apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: web-leader
  # namespace: server-leader
  labels:
    app: web-leader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "create","delete", "patch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
