apiVersion: v1
kind: Service
metadata:
  name: web-leader
  namespace: web-leader
spec:
  type: NodePort
  selector:
    app: web-leader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080